---
- name: URL check rulebook
  hosts: all
  sources:
    - name: MyUrlEventSource
      ansible.eda.url_check:
        urls: 
          - http://ec2-18-222-192-131.us-east-2.compute.amazonaws.com/oscap-reports/
        delay: 30
        verify_ssl: false
  rules:
    - name: Check for failed URL
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: restart_httpd
          organization: Default
