---
- name: URL check rulebook
  hosts: all
  sources:
    - name: MyUrlEventSource
      ansible.eda.url_check:
        urls: 
          - http://http://ec2-34-204-69-199.compute-1.amazonaws.com/oscap-reports/
        delay: 30
        verify_ssl: false
  rules:
    - name: Check for failed URL
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: restart_httpd
